INSERT INTO instituciones (
    AnioIncorporacion,
    NIT,
    Nombre,
    Logo,
    BannerInicial,
    ImagenVision,
    ImagenMision,
    Direccion,
    UbicacionGps,
    Telefono,
    Celular,
    Celular2,
    Celular3,
    Mision,
    Vision,
    Facebook,
    Tiktok,
    Instagram,
    PlataformaEducativa,
    Historia,
    Funciones,
    Caractisticas,
    Estado,
    Visibilidad
) VALUES
(
    '1998',
    '1029384756',
    'Instituto de Formación Artística María Luisa Luzio',
    'logos/luzio.png',
    'banners/luzio.jpg',
    'vision/luzio.jpg',
    'mision/luzio.jpg',
    'Av. Cívica Nº 245, Oruro',
    '-17.9647,-67.1060',
    '2523456',
    '72451234',
    NULL,
    NULL,
    'Formar profesionales en música y artes con excelencia académica.',
    'Ser referente nacional en educación artística superior.',
    'https://facebook.com/ifamluzio',
    NULL,
    'https://instagram.com/ifamluzio',
    'https://aulavirtual.luzio.edu',
    'El instituto fue fundado con el objetivo de fortalecer la educación musical en Bolivia.',
    'Formación académica, extensión cultural, investigación artística.',
    'Enfoque artístico, docentes especializados, infraestructura musical.',
    'ACTIVO',
    'PUBLICO'
),
(
    '2005',
    '5647382910',
    'Conservatorio Plurinacional de Música',
    'logos/conservatorio.png',
    'banners/conservatorio.jpg',
    'vision/conservatorio.jpg',
    'mision/conservatorio.jpg',
    'Calle Ayacucho Nº 112, La Paz',
    '-16.5000,-68.1500',
    '2214789',
    '71234567',
    '73456789',
    NULL,
    'Preservar y difundir la música boliviana y universal.',
    'Consolidarse como institución líder en formación musical.',
    'https://facebook.com/conservatoriomusica',
    'https://tiktok.com/@conservatoriomusica',
    'https://instagram.com/conservatoriomusica',
    'https://campus.conservatorio.edu.bo',
    'Institución creada para la profesionalización de músicos a nivel nacional.',
    'Docencia, investigación, difusión cultural.',
    'Formación clásica y folklórica, proyección social.',
    'ACTIVO',
    'PUBLICO'
),
(
    '2012',
    '9988776655',
    'Escuela Superior de Artes Escénicas',
    'logos/artesescenicas.png',
    'banners/artesescenicas.jpg',
    NULL,
    NULL,
    'Zona Central, Cochabamba',
    '-17.3895,-66.1568',
    NULL,
    '70112233',
    NULL,
    NULL,
    'Formar artistas escénicos con compromiso social.',
    'Ser una escuela innovadora en artes escénicas.',
    NULL,
    NULL,
    'https://instagram.com/artesescenicas',
    NULL,
    'La escuela surge como respuesta a la necesidad de formación teatral profesional.',
    'Formación actoral, producción escénica.',
    'Creatividad, expresión corporal, trabajo interdisciplinario.',
    'ACTIVO',
    'PRIVADO'
);


-- CARRERAS SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS
INSERT INTO carreras (
    instituciones_id,
    NombreCarrera,
    Descripcion,
    Area,
    Mencion,
    Resolucion,
    Programa,
    CantidadEvaluaciones,
    Nivel,
    Capacitacion,
    CarreraProfesional,
    Modalidad,
    Duracion,
    HorasTotales,
    TituloOficial,
    Estado,
    Visibilidad
) VALUES
(
    3,
    'Instrumentista en Piano',
    'Formación técnica superior orientada a la interpretación pianística.',
    'Música',
    'Piano',
    'R.M. 072/2024',
    'Anual',
    4,
    'TECNICO SUPERIOR',
    NULL,
    'INTERPRETACIÓN MUSICAL',
    'Presencial',
    '3 años',
    '3600',
    'Técnico Superior en Piano',
    'ACTIVO',
    'PUBLICO'
),
(
    3,
    'Instrumentista en Violín',
    'Carrera enfocada en la ejecución y técnica del violín.',
    'Música',
    'Violín',
    'R.M. 072/2024',
    'Anual',
    4,
    'TECNICO SUPERIOR',
    NULL,
    'INTERPRETACIÓN MUSICAL',
    'Presencial',
    '3 años',
    '3600',
    'Técnico Superior en Violín',
    'ACTIVO',
    'PUBLICO'
);
INSERT INTO carreras (
    instituciones_id,
    NombreCarrera,
    Descripcion,
    Area,
    Mencion,
    Resolucion,
    Programa,
    CantidadEvaluaciones,
    Nivel,
    Capacitacion,
    CarreraProfesional,
    Modalidad,
    Duracion,
    HorasTotales,
    TituloOficial,
    Estado,
    Visibilidad
) VALUES
(
    4,
    'Dirección Coral',
    'Formación en dirección y liderazgo de agrupaciones corales.',
    'Música',
    'Dirección Coral',
    'R.M. 015/2023',
    'Semestral',
    2,
    'TECNICO SUPERIOR',
    NULL,
    'DIRECCIÓN MUSICAL',
    'Presencial',
    '3 años',
    '3200',
    'Técnico Superior en Dirección Coral',
    'ACTIVO',
    'PUBLICO'
),
(
    4,
    'Educación Musical',
    'Carrera orientada a la enseñanza de la música en distintos niveles.',
    'Música',
    'Pedagogía Musical',
    'R.M. 015/2023',
    'Anual',
    4,
    'TECNICO SUPERIOR',
    NULL,
    'DOCENCIA MUSICAL',
    'Presencial',
    '3 años',
    '3400',
    'Técnico Superior en Educación Musical',
    'ACTIVO',
    'PUBLICO'
);
INSERT INTO carreras (
    instituciones_id,
    NombreCarrera,
    Descripcion,
    Area,
    Mencion,
    Resolucion,
    Programa,
    CantidadEvaluaciones,
    Nivel,
    Capacitacion,
    CarreraProfesional,
    Modalidad,
    Duracion,
    HorasTotales,
    TituloOficial,
    Estado,
    Visibilidad
) VALUES
(
    5,
    'Teatro Integral',
    'Formación actoral con énfasis en expresión corporal y escénica.',
    'Artes Escénicas',
    'Actuación',
    'R.M. 101/2022',
    'Anual',
    4,
    'CAPACITACION',
    'FORMACIÓN INFANTO JUVENIL',
    NULL,
    'Presencial',
    '2 años',
    '1800',
    'Certificado en Teatro Integral',
    'ACTIVO',
    'PUBLICO'
),
(
    5,
    'Danza Contemporánea',
    'Capacitación artística en técnicas de danza contemporánea.',
    'Artes Escénicas',
    'Danza',
    'R.M. 101/2022',
    'Semestral',
    2,
    'CAPACITACION',
    'FORMACIÓN ARTÍSTICA',
    NULL,
    'Presencial',
    '2 años',
    '1600',
    'Certificado en Danza Contemporánea',
    'ACTIVO',
    'PUBLICO'
);
